### ISSUE TITLE
Event reader is broken

### ISSUE THREAD

**Issue by sizun** [cta-observatory/ctapipe_io_nectarcam#11]
Event reader no longer works with ctapipe master. Due at least to changes in containers by PR https://github.com/cta-observatory/ctapipe/pull/1267 and PR https://github.com/cta-observatory/ctapipe/pull/1294.

**Comment by sizun** [comment]
@jlenain , @FrancaCassol Do you think we could freeze the ctapipe version in the nectarchain environment file to an older version still compatible with the current ctapipe_io_nectarcam ? Is is possible to specify a commit hash?

**Comment by MaxNoe** [comment]
Yes it is, you can use `git+https://github.com/cta-observatory/ctapipe@<hash>`

**Comment by MaxNoe** [comment]
But the next version of ctapipe will be out this week if not something unforeseen happens. We are wrapping up the last PRs and issues for 0.8

**Comment by jlenain** [comment]
@sizun , `ctapipe` is currently installed via `conda` from the environment file of `nectarcahin`, and we agreed it should depend on the master of `ctapipe`. So `ctapipe_io_nectarcam` should be adapted to reflect the recent changes in `ctapipe`. I guess it should only be a matter of renaming a few `import` statement.

As a temporary workaround, you can force a particular version to be installed from the `nectarchain` environment file with e.g.:
`  - ctapipe=0.7.0`
in the `dependencies` section.

**Comment by MaxNoe** [comment]
@jlenain The changes for ctapipe 0.8 go a bit deeper than this and will require some changes to the event source.

E.g. event source will be required to provide `subarray`, `obs_id` and `datalevels` as a property to be accessed outside the event loop.

**Comment by jlenain** [comment]
Hi @MaxNoe , OK, thanks for the information. I was not aware of the detailed ongoing changes.

So, @sizun , in the meantime, I would indeed suggest to force the use of version `0.7.0` in `nectarchain` while the event source is being updated.

**Comment by sizun** [comment]
I am not sure the event source is still compatible with 0.7.0. Anyway, I have started looking into the changes I understand.

**Comment by MaxNoe** [comment]
@jlenain we will provide a changelog as soon as the new version is out

**Comment by sizun** [comment]
Fixed by https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/12
