### ISSUE TITLE
Needs update for ctapipe-0.12 and dependencies

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe_io_nectarcam#17]
Since people are staring to use ctapipe for nectarcam studies, having it be compatible with a reasonably recent ctapipe would be useful.

## Model updates

There are a number of changes that need to be made to be compatible with ctapipe-0.12's data model and instrument model.

for example, in `__init__.py`,  the SubarrayDescription is not constructed correctly, specifically  a CameraGeometry is passed where a CameraDescription (with a CameraGeometry and CameraReadout) should be constructed.  

It would be good to check the ctapipe version in the code as well and ensure that it is compatible.

## dependency updates

* RIght now, the env files specify a ctapipe version that is a git hash (master at 22.02.2019), rather than using the released packages. It would be better to use a release version, which are all in conda-forge now.
* setup.py doesn't restrict to any ctapipe version

**Comment by kosack** [comment]
from a conversation with Floriane:

```py3
This is this kind of file : NectarCAM.Run1721.0001.fits.fz. And here is the code with the error: 

from ctapipe.io import EventSource, EventSeeker
from ctapipe import utils
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline
from protozfits import File

path = "/Users/fcangemi/nectarchain/obs/NectarCAM.Run1721.0001.fits.fz"
reader = EventSource(input_url = path)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/83/j4xppqld0cgfm3_rq_b_cbms0f4lpt/T/ipykernel_14775/171585135.py in <module>
     1 #path = utils.get_dataset_path("gamma_test_large.simtel.gz")
     2 path = "/Users/fcangemi/nectarchain/obs/NectarCAM.Run1721.0001.fits.fz"
----> 3 reader = EventSource(input_url = path)

/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe_io_nectarcam/__init__.py in __init__(self, **kwargs)
    81         self.log.info("Read {} input files".format(self.multi_file.num_inputs()))
    82         self._tel_id = self.camera_config.telescope_id
---> 83         self._subarray_info = self.prepare_subarray_info(self._tel_id)
    84 
    85     @property

/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe_io_nectarcam/__init__.py in prepare_subarray_info(self, tel_id)
   113 
--> 114         tel_descr = TelescopeDescription(name='MST', tel_type='NectarCam', optics=optics, camera=camera)
   115         tel_descr.optics.tel_subtype = ''  # to correct bug in reading
   116 

/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/instrument/telescope.py in __init__(self, name, tel_type, optics, camera)
    58 
    59         if not isinstance(camera, CameraDescription):
---> 60             raise TypeError("`camera` must be an instance of `CameraDescription`")
    61 
    62         self.name = name

TypeError: `camera` must be an instance of `CameraDescription`
```

**Comment by maxnoe** [comment]
This needs a maintainer from the nectarcam team. 

If one is found, I can offer support what was needed in `ctapipe_io_lst` to make this a valid event source.

**Comment by maxnoe** [comment]
We could probably also talk about merging the two repositories (at this point probably rather adding NectarCam support to ctapipe_io_lst) e.g. in a `ctapipe_io_zfits`

**Comment by kosack** [comment]
ctapipe_io_zfits would be nice.  I guess the main difference in the LST version is all of the ring-sampler and glitch corrections that are not needed for NectarCam, but the core ZFITS reading code should be nearly identical

**Comment by tibaldo** [comment]
I discussed this issue with @FrancaCassol and it would be relatively straighforward for me to modify ctapipe-io_nectarcam so that it works with the latest version of ctapipe I guess. In the longer run I guess it makes more sense to have everything that is not instrument-dependent in the zfits reader, but in the mean time I could adapt the existing code if that makes sense.

**Comment by FrancaCassol** [comment]
Hi, there are some differences in the camera specific data model (which should be not a problem), but I am afraid also in the handling of Cat-A pedestal and calibration data, however I think that for nectarCAM this is not completely defined yet (work is starting on the topics). I agree with the proposal of @maxnoe of merging  the two readers, but in the meanwhile it is  better to make the nectarCAM reader working again, as suggested by @tibaldo, in order to have a working base to start.

**Comment by tibaldo** [comment]
Okay, I can look into this in the next few days, and as soon as I have a working solution I'll make a pull request then.

**Comment by tibaldo** [comment]
I implemented all the changes discussed and made a pull request, see #18
