### ISSUE TITLE
Make it possible to read files that contain events with waveforms of improper shape

### ISSUE THREAD

**Issue by tibaldo** [cta-observatory/ctapipe_io_nectarcam#21]
Pierre Jean reported an error that occurs when in `fill_r0_camera_container_from_zfile` an event with waveform that does not match the expected shape is encountered. Currently an error is raised, so the entire file cannot be read.
While the persons responsible of the event builder are alerted and a definitive fix should be worked out there, it would be valuable to read existing files with corrupted events into ctapipe. I would propose to change the error into a warning, reject the individual corrupted event and continue reading the file.

**Comment by sizun** [comment]
If you encounter new runs with this symptom (more recent than run 3112), please reopen [issue 51350](https://redmine.cta-observatory.org/issues/51350) and report them.

**Comment by jlenain** [comment]
To be followed on [issue 51350](https://redmine.cta-observatory.org/issues/51350)
