### ISSUE TITLE
Precision of astropy time

### ISSUE THREAD

**Issue by sizun** [cta-observatory/ctapipe_io_nectarcam#24]
The field event.trigger.time is filled with an instance of astropy.time.core.Time built from the raw nanosecond count time from the UCTS:

https://github.com/cta-observatory/ctapipe_io_nectarcam/blob/e57e32207f633850e000675f40543e5c3dc3ef9c/ctapipe_io_nectarcam/__init__.py#L392-L394

When computing time differences, this results in a loss of precision.
For example, in run 3462, it results in a minimum delta-t of 512 ns instead of 727 ns.

Given 2 UCTS timestamps that differ by 741 ns:
```
tucts_1 = 1659704534052529046
tucts_2 = tucts_1 + 741
```
the resulting times differ by 512 ns:
```
from ctapipe_io_nectarcam import time_from_unix_tai_ns
t_1 = time_from_unix_tai_ns(tucts_1)
t_2 = time_from_unix_tai_ns(tucts_2)
(t_2 - t_1).to(u.ns).value
```

unless there is another way to manipulate Time without loss of precision?

**Comment by tibaldo** [comment]
Hi Patrick, I don't think the problem is with astropy Time, but rather with the function time_from_unix_tai_ns that converts the timestamp into a Time object. It looks to me like the precision of the fractional seconds handling in that function is not enough. Yet, at the moment I don't know how to fix it.

**Comment by maxnoe** [comment]
The bug is somehow having `S_TO_NS` be a `np.uint64`. With `S_TO_NS = int(1e9)` it works as expected. I am not yet sure why this is the case.

**Comment by maxnoe** [comment]
This is a **very** unfortunate property of numpy and something which there is an open issue about but which very probably will never really be fixed since it will be a major breakage:

https://github.com/numpy/numpy/issues/5745

**Comment by maxnoe** [comment]
Adding a cast to the `time_from_unix_tai_ns` function solves the issue:

```
import numpy as np
from astropy.time import Time
import astropy.units as u

S_TO_NS = np.uint64(1e9)

t1 = 1659704534052529046
t2 = t1 + 741

print(t2 - t1)


def time_from_unix_tai_ns(unix_tai_ns):
    '''
    Create an astropy Time instance from a unix time tai timestamp in ns.
    By using both arguments to time, the result will be a higher precision
    timestamp.
    '''
    unix_tai_ns = np.asanyarray(unix_tai_ns).astype(np.uint64)
    full_seconds = unix_tai_ns // S_TO_NS
    fractional_seconds = (unix_tai_ns % S_TO_NS) / S_TO_NS
    return Time(full_seconds, fractional_seconds, format='unix_tai')


time1 = time_from_unix_tai_ns(t1)
time2 = time_from_unix_tai_ns(t2)

# note: this does only effect display, not actual precision
time1.precision = 9
time2.precision = 9

print(time1.iso)
print(time2.iso)

print((time2 - time1).to_value(u.ns))
```

However, this should not affect actual nectarcam data, since for actual nectarcam data, this value should already be a `np.uint64`, not a python `int`

**Comment by sizun** [comment]
Thanks for your feedback. The current ctapipe_io_nectarcam uses struct.unpack to decode the CDTS data and ucts_timestamp ends up being an int. I see the LST reader uses np.dtype which decodes ucts_timestamp as a np.uint64.
Should I just copy the relevant code from LST?

**Comment by sizun** [comment]
Or just add the cast you suggested?

**Comment by maxnoe** [comment]
I would do both, actually. Using numpy to read those values is a lot faster, the cast is chrap and enable to use the function on python Inputs.
